### ISSUE TITLE
Wrong message in GitLabHook

### ISSUE THREAD

**Issue by Kerl13** [Kerl13/GHA#15]
When a committer pushes on a branch concerned by a merge request, the message given by GHA is `<committer> opened merge request <id>`.

"updated" would be more appropriate than "opened"

**Comment by Niols** [comment]
This is because I'm using the current 'state' instead of an action (see https://github.com/Niols/GHA/blob/master/GitLabHooks.py#L95).
One would need to take a look at webhooks in the merge requests' cases to see what usable information they contain (would also help for #16)

**Comment by Kerl13** [comment]
Closed by 454e475
