### ISSUE TITLE
Broken link in GitLabHook

### ISSUE THREAD

**Issue by Kerl13** [Kerl13/GHA#16]
The link given by GHA when it tells about a merge request is broken

**Comment by Niols** [comment]
Sadly, when I wrote GHA, GitLab wasn't providing a link in its WebHooks, so I had to build it myself with the commit numbers. I guess that there's something during the merge that makes that link unusable.

If I'm correct, a merge is just a particular pull, which means that the generated URL is: `<repo-url>/compare/<commit-before>...<commit-after>` (https://github.com/Niols/GHA/blob/master/GitLabHooks.py#L53).
What would be the right URL?
